name: "Release"

# Build the desktop app with code from ente-io/ente and create/update a release.
#
# For more details, see `docs/release.md` in ente-io/ente.

on:
  # Trigger manually or `gh workflow run desktop-release.yml --source=foo`.
  workflow_dispatch:
    inputs:
      source:
        description: "Branch (ente-io/ente) to build"
        type: string
  schedule:
    # Run every weekday at ~8:00 AM IST.
    # See: [Note: Run workflow every 24 hours]
    #
    - cron: "45 2 * * 1-5"
  push:
    # Run when a tag matching the pattern "vd.d.d" is pushed. In particular,
    # this excludes the "-beta" tags.
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: desktop

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # If triggered by a tag, checkout photosd-$tag from the source
          # repository. Otherwise checkout $source (default: "main").
          repository: anandbaburajan/ente
          ref: "${{ startsWith(github.ref, 'refs/tags/v') &&
            format('photosd-{0}', github.ref_name) || ( inputs.source
            || 'main' ) }}"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Increase yarn timeout
        # `yarn install` times out sometimes on the Windows runner,
        # resulting in flaky builds.
        run: yarn config set network-timeout 900000 -g

      - name: Install dependencies
        run: yarn install

      - name: Build
        uses: ente-io/action-electron-builder@eff78a1d33bdab4c54ede0e5cdc71e0c2cf803e2
        with:
          package_root: desktop
          build_script_name: build:ci

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Passes `--publish always` to electron-builder
          release: true
        env:
          # Default is "draft", but since our nightly builds update
          # existing pre-releases, set this to "prerelease".
          EP_PRE_RELEASE: true
          # By default, electron-builder does not update releases that
          # were more than 2 hours ago. Override this to allow us to
          # continually update our nightly pre-releases.
          EP_GH_IGNORE_TIME: true
          # Workaround recommended in
          # https://github.com/electron-userland/electron-builder/issues/3179
          USE_HARD_LINKS: false
